### ISSUE TITLE
Error response from daemon: pull access denied for ml/project1, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by Gavin-Evans** [ming0070913/example-ml-project#1]
hi,
Firstly, run docker_build.sh by bash. 
However, I encounter a problem when run docker_run.sh by bash. 
as follows:
![image](https://user-images.githubusercontent.com/47597201/145739475-74c52442-58ae-404e-9b4e-154dac01ef18.png)
emem...., how to deal with it? 
thanks

**Comment by Gavin-Evans** [comment]
I'm sorry,
and would like to give you a piece of  advice.
could you offer usages for your project detailly?
thanks

**Comment by ming0070913** [comment]
Hi, `docker_run.sh` is an example of pulling from a docker registry. 
Instead, you should build the docker yourself and just use `docker run` to start the image. 
```bash
docker run -d \
  --rm \
  --gpus all \
  -p ${API_PORT}:80 \
  -e "WORKERS=${WORKERS}" \
  -e "TIMEOUT=${TIMEOUT}" \
  -e "PYTHON_ENV=${PYTHON_ENV}" \
  -v "${LOG_FOLDER}:/app/log" \
  --name="${JOB_NAME}" \
  ${IMAGE}:${TAG}
```
